# Generated by Django 4.2.14 on 2025-07-07 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(blank=True, max_length=100, null=True)),
                ('lastname', models.TextField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('telegram_nickname', models.CharField(blank=True, max_length=32, null=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('data_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_hire', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
