# Generated by Django 4.2.14 on 2025-07-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='count_of_done_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='count_of_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
