# Generated by Django 4.2.14 on 2025-07-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_count_of_done_tasks_profile_count_of_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_confirmation_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
