# Generated by Django 4.2.14 on 2025-08-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_system', '0002_alter_taskmodel_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
